apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
spec:
  containers:
    - name: my-nginx-app
      image: rahma310/nginx-test
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80